### ISSUE TITLE
No output on Apple M1

### ISSUE THREAD

**Issue by dblanchard** [robinmanuelthiel/speedtest#1]
I'm very new to Docker but have run speedtest-cli before, from within bash. When I run the docker image from the bash prompt, I get no output at the bash prompt. Ihave successfully run `docker run hello-world` to ensure docker is running correctly.

**Comment by robinmanuelthiel** [comment]
It can take a while until the speedtest is finished, but you should see something like this:

![image](https://user-images.githubusercontent.com/5874465/138317900-d2d79499-a1bc-4b13-8216-4d7d7ef39a1b.png)

**Comment by robinmanuelthiel** [comment]
Hey @teddy931130, I have just pushed an update. Can you please check, if the new `robinmanuelthiel/speedtest:latest` Docker image works for you? You might need to pull the update fist with `docker pull robinmanuelthiel/speedtest:latest`. Otherwise, you can also specify the ARM container directly now: `robinmanuelthiel/speedtest:latest-arm64v8`

**Comment by teddy931130** [comment]
Yep, works for me on the M1 MacBook Air! Thanks!
What did you change? just the base image which is now `debian:bullseye`? I see it has `linux/ppc64le` architecture

**Comment by robinmanuelthiel** [comment]
@teddy931130, yep I've removed `FROM arm32v7/debian` so that the architecture is not fixed to arm32 anymore.

Also, I've updated the Release Pipeline in GitHub Actions to include multiple platforms as you can see blow.

```yaml
docker buildx build \
    --push \
    --platform linux/arm/v7,linux/arm64/v8,linux/amd64 \
    --tag robinmanuelthiel/speedtest:${{ github.event.inputs.version }} \
    --tag robinmanuelthiel/speedtest:latest \
    .
```

**Comment by teddy931130** [comment]
Awesome! Thanks for your efforts!
