### ISSUE TITLE
JQ not found error

### ISSUE THREAD

**Issue by mauritsderuiter95** [robinmanuelthiel/speedtest#3]
Hi Robin,

I got a few errors running the script. It says it couldn't find jq and then it couldn't divide the DOWNLOAD var by 125000, which makes sense.

**Comment by mauritsderuiter95** [comment]
See [https://github.com/robinmanuelthiel/speedtest/pull/4](url) for a fix.

**Comment by robinmanuelthiel** [comment]
Interesting, I had in in the Dockerfile initially: https://github.com/robinmanuelthiel/speedtest/commit/64cddf19d15cc7a59d7280f4a7b6339dae6c6e41#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557

But as I had the impression, it is not used anymore, I kicked it out. Will bring it back in. Thanks for your PR!

**Comment by robinmanuelthiel** [comment]
Version 0.2.1 should have solved that!
