### ISSUE TITLE
Please add ping/latency metrics

### ISSUE THREAD

**Issue by airus-pty-ltd** [robinmanuelthiel/speedtest#6]
Hi.

I like what you've done with the dash/grafana/influx integration - simple and effective, up and running in a couple of minutes. Could I suggest you add a ping/latency metric alongside, also? It might well be that you're scraping this already and I've not paid close enough attention. 

Thanks again for building this little docker fleet out. Really handy and appreciated.

**Comment by robinmanuelthiel** [comment]
@ignacioborrajo added the ping feature in https://github.com/robinmanuelthiel/speedtest/pull/5, so it gets collected and written to the database. It's just not visualized in the demo dashboard yet.
